baseURL = "https://lenhan231.github.io/hugo_aws/"
title = "hugo_aws"
relativeURLs = true
canonifyURLs = true

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "thienlh@thienlu.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableSearch = true
  disableLanguageSwitchingButton = false
  custom_css = ["css/custom.css"]

[languages]
  [languages.en]
  title = "Internship Report"
  weight = 1
  languageName = "English"

  [[languages.en.menu.shortcuts]]
  name = "<i class='fab fa-facebook'></i> AWS Study Group"
  identifier = "AWS Study Group FB"
  url = "https://www.facebook.com/groups/awsstudygroupfcj/"
  weight = 20

  [languages.vi]
  title = "Báo cáo thực tập"
  weight = 2
  languageName = "Tiếng Việt"

  [[languages.vi.menu.shortcuts]]
  name = "<i class='fab fa-facebook'></i> AWS Study Group"
  identifier = "AWS Study Group FB"
  url = "https://www.facebook.com/groups/awsstudygroupfcj/"
  weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
